### ISSUE TITLE
Sublime Text 2/3 Syntax Highlighter

### ISSUE THREAD

**Issue by dre1080** [yosssi/gold#14]
It would be nice if there was a syntax highlighter for Sublime Text.
Any plans on this?

**Comment by yosssi** [comment]
@dre1080 Thanks for your comment! I will try to create a syntax highlighter for Sublime Text. Just a moment, please!

**Comment by dre1080** [comment]
@yosssi Thanks! Really like this package. :+1: Wanna use it for a new project.

**Comment by yosssi** [comment]
@dre1080 Hi, I created a syntax highlighter for Sublime Text. Please visit the following repository for the details.

[gold-tmbundle](https://github.com/yosssi/gold-tmbundle)

Thanks.

**Comment by dre1080** [comment]
Thanks

**Comment by yosssi** [comment]
You're welcome!
