### ISSUE TITLE
Specify custom delimiters

### ISSUE THREAD

**Issue by tabula-rasa** [yosssi/gold#21]
Hi, is there any possibility to specify custom delimiters, like so: http://golang.org/pkg/text/template/#Template.Delims

**Comment by yosssi** [comment]
Thanks for your issue. I added the function you want on Gold. Please specify custom delimiters such as the following:

``` go
var g = gold.NewGenerator(true).Delims("[[", "]]")
```

**Comment by tabula-rasa** [comment]
Ty :)
