### ISSUE TITLE
Meta tags dont parse

### ISSUE THREAD

**Issue by dariusc93** [yosssi/gold#23]
Hi, I really am interested in gold and been wanting to keep my previous work compatible (since gold is almost like jade) but I notice that the meta tags dont parse like they should. When it is parsed into html, I get

<meta(http-equiv=content-type content="text/html;" charset="utf-8)"></meta(http-equiv=content-type>

Is there something I am missing or a specific way of doing this?

**Comment by yosssi** [comment]
Thanks for your contact. Could you give me your Gold template code?

**Comment by dariusc93** [comment]
Here is an example for one of the pages that get the error. https://gist.github.com/dariusc93/5459a66382a93210254f 

You will also notice that for some reason the meta gets cut off into the body (cant find out why).

**Comment by yosssi** [comment]
@dariusc93 

I fixed some of your template:

https://gist.github.com/yosssi/a52ba0655c9938c643b5

Could you try this?

BTW, I'm refining Gold and creating a new HTML template engine:

https://github.com/yosssi/ace

I have managed Gold for 7 months and this engine has come to have a bit messy codes and APIs, so I decided to re-create new one.

I've almost finished creating Ace, so if you are interested in this, please check it out.

Thanks.

**Comment by dariusc93** [comment]
Thank you and yes I will give it a check out.

**Comment by yosssi** [comment]
@dariusc93 
Thanks!
I'm now writing the documents about Ace and they will be shown up in few hours!
https://github.com/yosssi/ace/tree/master/documentation
