### ISSUE TITLE
Conditional attributes

### ISSUE THREAD

**Issue by adamzy** [yosssi/gold#6]
Hi, thanks for this lovely package.
I was wondering how to add some conditional attributes to a tag.
For example, one can do this in `amber`:

```
div
    .hasfriends ? Friends > 0
```

In `gold`, the following does not work as it creates another `div`.

```
div
    {{if gt .Friends 0}} 
       .hasfriends 
    {{end}}
```

BTW, is there any rule to indent the {{...}} expression in the template?

**Comment by yosssi** [comment]
@adamzy Hi, thanks for your comment. You can use the [html/template](http://golang.org/pkg/html/template/) express in Gold.

For example, you can write the following expression:

``` gold
div
    {{if .Friends > 0}} 
       .hasfriends 
    {{end}}
```

You have to use a tab or two spaces as an indent.

**Comment by yosssi** [comment]
@adamzy Sorry, I was wrong. Your notation looks correct. Could you show me a source code that calls a gold generator?

**Comment by adamzy** [comment]
@yosssi Hi, Thanks for the fast reply. 
I think this tiny example shows it:

``` go
package main
import (
    "github.com/yosssi/gold"
    "os"
)
var g = gold.NewGenerator(false)

func main() {
    s := `
div
  {{if gt .Friends 0}} 
    .hasfriends 
  {{end}}
`
    tpl, _ := g.ParseString(map[string]string{"main":s}, "main")
    data := map[string]interface{}{"Friends": 9}
    tpl.Execute(os.Stdout, data)
}
```

The output is 

``` html
<div>
<div class="hasfriends"></div>
</div>
```

while the desired output is

``` html
<div class="hasfriends"> </div>
```

**Comment by yosssi** [comment]
@adamzy Thanks for your reply. You can write the following:

``` gold
{{if gt .Friends 0}}
  .hasfriends
{{end}}
```

`.hasfriends` will be converted to `<div class="hasfriends"></div>`. You can get more information by seeing [this part of the README](https://github.com/yosssi/gold#ids-and-classes). This is the [Slim](http://slim-lang.com/) style.

If you want to add `hasfriends` class on the div element only if `Friends > 0`, you can write as the following:

``` gold
div class="{{if gt .Friends 0}}hasfriends{{end}}"
```

or, you can move the conditions from the template to the Go source code:

``` go
package main

import (
    "os"

    "github.com/yosssi/gold"
)

var g = gold.NewGenerator(false)

func main() {
    s := `
div class={{.divClass}}
`
    tpl, _ := g.ParseString(map[string]string{"main": s}, "main")
    friends := 9
    divClass := ""
    if friends > 0 {
        divClass = "hasfriends"
    }
    data := map[string]interface{}{"divClass": divClass}
    tpl.Execute(os.Stdout, data)
}
```

**Comment by adamzy** [comment]
@yosssi Thanks for the explaination. You are very nice.
I think the second approach is more versatile, and it works for this case

```
tr class="{{if gt .Progress 0}}active{{end}}"
  td {{.Name}}
  td {{.Progress}}
```

while the frist one doesn't work?

```
{{if gt .Progress 0}}
  tr.active
{{else}}
  tr
{{end}}
  td {{.Name}}
  td {{.Progress}}
```

BTW, is there any plan to add pretty-print feature?

**Comment by yosssi** [comment]
@adamzy Thanks for your reply. For now, Gold can not parse the following case correctly:

``` gold
{{if gt .Progress 0}}
  tr.active
{{else}}
  tr
{{end}}
  td {{.Name}}
  td {{.Progress}}
```

You have to write the following code:

``` gold
{{if gt .Progress 0}}
  tr.active
    td {{.Name}}
    td {{.Progress}}
{{else}}
  tr
    td {{.Name}}
    td {{.Progress}}
{{end}}
```

I'll consider how to handle with this case.

In addition, thanks for your proposal for the pretty-print feature! I will try to implement this feature ASAP!

**Comment by yosssi** [comment]
@adamzy I noticed that I have to format the [Template.Execute](http://golang.org/pkg/html/template/#Template.Execute) result to add the pretty-print feature. It might take some time to add this feature. I will continue to tackle with this issue.

**Comment by adamzy** [comment]
@yosssi I think adding this feature is not an urgent, but it would make this package better.
Hope `gold` will become more and more popular in Go, just as Jade and Slim in Node and Ruby.

**Comment by yosssi** [comment]
@adamzy Thank you very much! I will keep making this package better and better.

**Comment by yosssi** [comment]
@adamzy Hi, I added the pretty-print feature on Gold! 

You can format the result HTML source codes by using [GoHTML](https://github.com/yosssi/gohtml) package I created. [gohtml.Writer](https://godoc.org/github.com/yosssi/gohtml#Writer) formats HTML source codes and writes them.

Example:

``` go
package main

import (
    "os"

    "github.com/yosssi/gohtml"
    "github.com/yosssi/gold"
)

var g = gold.NewGenerator(false)

func main() {
    // template strings
    parent := `
doctype html
html
  head
    title Gold
  body
    block content
    footer
      block footer
`
    child := `
extends parent

block content
  #container
    = .Msg

block footer
  .footer
    | Copyright XXX
`

    stringTemplates := map[string]string{"parent": parent, "child": child}

    tpl, err := g.ParseString(stringTemplates, "child")

    if err != nil {
        panic(err)
    }

    data := map[string]interface{}{"Msg": "Hello, Gold!"}

    err = tpl.Execute(gohtml.NewWriter(os.Stdout), data)

    if err != nil {
        panic(err)
    }
}
```

Output:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>
      Gold
    </title>
  </head>
  <body>
    <div id="container">
      Hello, Gold!
    </div>
    <footer>
      <div class="footer">
        Copyright XXX
      </div>
    </footer>
  </body>
</html>
```

Please get the latest version of Gold and check this pretty-print feature out!

Thanks!

**Comment by adamzy** [comment]
@yosssi Thanks! It is works great now. Really helpful!

**Comment by yosssi** [comment]
@adamzy Thanks for your reviewing!
